Fix TestAccResourceNcloudServer_classic_basic
=== RUN   TestAccResourceNcloudServer_classic_basic
--- FAIL: TestAccResourceNcloudServer_classic_basic (232.95s)
panic: interface conversion: interface {} is nil, not *ncloud.ProviderConfig [recovered]
	panic: interface conversion: interface {} is nil, not *ncloud.ProviderConfig